---
# Requires: 
#  ansible-galaxy collection install hetzner.hcloud
#
# References:
# - https://docs.ansible.com/ansible/latest/collections/hetzner/hcloud/hcloud_server_module.html
# - https://github.com/ansible-collections/hetzner.hcloud
# - https://docs.hetzner.cloud/#servers-create-a-server
# - https://community.hetzner.com/tutorials/basic-cloud-config

- name: Create Hetzner Cloud Server
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Create a basic server with ssh key
      hcloud_server:
        # api_token: "...."         # or use env var HCLOUD_TOKEN
        name: jw-ansible-deployed
        server_type: cx11
        image: ubuntu-22.04
        location: fsn1
        ssh_keys:
          - jw@owncloud.com             # known in QA project
        # enable_ipv6: false            # huch, unsupported parameter??
        user_data: "#cloud-config\nruncmd:\n- touch /root/cloud-init-worked\n- uname -a\n- uname -a > /tmp/cloud-config.out"        # Cloud-Init user data. max 32KiB.
        state: started                  # started: create server, absent: remove the server
      register: server                  # stdout/stderr of cloud-init is not captured.
    
    - debug: var=server

    - name: Print server IP address
      debug:
        var: server.hcloud_server.ipv4_address
