---
- hosts: all
  name: Fabtop Install Play
  tasks:
  - name: add inkscape ppa
    apt_repository: 
      repo: 'ppa:inkscape.dev/stable-1.1'
      state: present
      update-cache: true

  - name: install inkscape package
    become: true
    become_user: root
    apt:
      state: present
      name:
        - inkscape

    

